### ISSUE TITLE
QUESTION - OpenSuse is supported?

### ISSUE THREAD

**Issue by DimSystem** [desbma/shh#7]
Hi there! Can't believe that I found this hidden gem!

Im on opensuse tumbleweed, i see there is no oficial support. Should I compile from source and hope for the best?
Any tests with opensuse?

Thank you!

**Comment by desbma** [comment]
Hi,

Currently I have tested it on Debian, Ubuntu and Arch Linux. However it should work on any distribution that has a recent version of systemd, strace, and the Linux kernel.

Please test and open issues if it doesn't!
